"""empty message

Revision ID: 7d98f1db80da
Revises: 
Create Date: 2021-08-20 21:52:27.221107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d98f1db80da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opponents',
    sa.Column('opponent_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('score', sa.Boolean(), nullable=True),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('opponent_id')
    )
    with op.batch_alter_table('opponents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opponents_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_opponents_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_opponents_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_opponents_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_opponents_team_name'), ['team_name'], unique=False)

    op.create_table('positions',
    sa.Column('position_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_position'), ['position'], unique=False)

    op.create_table('players',
    sa.Column('player_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('jersey_no', sa.String(length=50), nullable=False),
    sa.Column('pa_1', sa.Integer(), nullable=True),
    sa.Column('pm_1', sa.Integer(), nullable=True),
    sa.Column('pa_2', sa.Integer(), nullable=True),
    sa.Column('pm_2', sa.Integer(), nullable=True),
    sa.Column('pa_3', sa.Integer(), nullable=True),
    sa.Column('pm_3', sa.Integer(), nullable=True),
    sa.Column('fouls_o', sa.Integer(), nullable=True),
    sa.Column('fouls_d', sa.Integer(), nullable=True),
    sa.Column('rebounds_o', sa.Integer(), nullable=True),
    sa.Column('rebounds_d', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('id_positon', sa.Integer(), nullable=False),
    sa.Column('id_opponent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_opponent'], ['opponents.opponent_id'], ),
    sa.ForeignKeyConstraint(['id_positon'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_assists'), ['assists'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_blocks'), ['blocks'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_fouls_d'), ['fouls_d'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_fouls_o'), ['fouls_o'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_jersey_no'), ['jersey_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_pa_1'), ['pa_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_pa_2'), ['pa_2'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_pa_3'), ['pa_3'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_pm_1'), ['pm_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_pm_2'), ['pm_2'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_pm_3'), ['pm_3'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_rebounds_d'), ['rebounds_d'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_rebounds_o'), ['rebounds_o'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_steals'), ['steals'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_turnovers'), ['turnovers'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_turnovers'))
        batch_op.drop_index(batch_op.f('ix_players_steals'))
        batch_op.drop_index(batch_op.f('ix_players_rebounds_o'))
        batch_op.drop_index(batch_op.f('ix_players_rebounds_d'))
        batch_op.drop_index(batch_op.f('ix_players_pm_3'))
        batch_op.drop_index(batch_op.f('ix_players_pm_2'))
        batch_op.drop_index(batch_op.f('ix_players_pm_1'))
        batch_op.drop_index(batch_op.f('ix_players_pa_3'))
        batch_op.drop_index(batch_op.f('ix_players_pa_2'))
        batch_op.drop_index(batch_op.f('ix_players_pa_1'))
        batch_op.drop_index(batch_op.f('ix_players_jersey_no'))
        batch_op.drop_index(batch_op.f('ix_players_full_name'))
        batch_op.drop_index(batch_op.f('ix_players_fouls_o'))
        batch_op.drop_index(batch_op.f('ix_players_fouls_d'))
        batch_op.drop_index(batch_op.f('ix_players_blocks'))
        batch_op.drop_index(batch_op.f('ix_players_assists'))

    op.drop_table('players')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_position'))

    op.drop_table('positions')
    with op.batch_alter_table('opponents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opponents_team_name'))
        batch_op.drop_index(batch_op.f('ix_opponents_score'))
        batch_op.drop_index(batch_op.f('ix_opponents_result'))
        batch_op.drop_index(batch_op.f('ix_opponents_points'))
        batch_op.drop_index(batch_op.f('ix_opponents_date'))

    op.drop_table('opponents')
    # ### end Alembic commands ###
